### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by dushyantahuja** [lbernstone/asyncUpdate#3]
Hi,

Thanks for creating this - I'm using this for one of my personal projects. The upload works great, except that once the upload is completed, instead of showing the "Please wait while the device reboots" and redirecting to the home page, I get "This site can't be reached" error. The URL shows <IP Address>/doUpdate.

The full code is available here:
https://github.com/dushyantahuja/SmallInfinityMirror/tree/rc2-spiffs

Can you please help.

**Comment by Saur0o0n** [comment]
It (I guess) should be like this:
```
  if (final) {
    AsyncWebServerResponse *response = request->beginResponse(200, "text/plain", "Please wait while the device reboots...");
    response->addHeader("Refresh", "30; url=/about.html");
    response->addHeader("Connection", "close");
    request->send(response);
```

because Location: (with response 30x) makes browser immediately  go to / and then set refresh in 20s. But browser cannot reach web server because it's restarting. With my example you will get text message about device restarting and after 30 seconds browser will go to specified URL - after 30s device should be restarted already.

**Comment by dushyantahuja** [comment]
Thanks a lot - will make the changes.
